services:
  backend:
    build: .
    ports:
      - '5000:5000'
    # environment:
    #   NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - /var/www/diploma/uploads:/usr/src/app/uploads
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
